name: itineris
channels:
  - conda-forge
dependencies:
  # naavre-fl-*-cell-build
  - r-jsonlite
  - r-optparse
  # naavre-fl-*-jupyter
  - ipykernel=6.29.5
  - r-irkernel=1.3.2
  # user packages for all flavors
  - git=2.49.0
  - jq>=1.8
  - minio=7.2.15
  - pip=25.0.1
  - python>=3.8
  - r=4.5
  - r-secretsprovider
  - r-getpass
  - r-aws.s3
  - pip:
    - SecretsProvider
  # user packages for this flavor
  # (intentionally empty in vanilla)
