name: pclake
channels:
   - conda-forge
dependencies:
  # naavre-fl-*-cell-build
  - r-jsonlite>=1.9.1
  - r-optparse>=1.7.5
  # naavre-fl-*-jupyter
  # - ipykernel>=6.29.5
  - r-irkernel>=1.3.2
  # user packages for all flavors
  - git>=2.39.1
  - jq>=1.8
  - minio>=7.2.15
  # - pip>=25.0.1
  # - python>=3.8
  - r>=4.4
  - r-secretsprovider
  - r-getpass
  - r-aws.s3
  # - pip:
  #   - SecretsProvider
  # user packages for this flavor
  - r-desolve
  - r-rjava
  - r-reshape2
  - r-ggplot2
  - r-xlconnect
  - r-readxl
  - r-plyr
  - r-tidyr
  - r-devtools
  - r-usethis
