name: biotope
channels:
  - conda-forge
dependencies:
  # naavre-fl-*-cell-build
  - r-jsonlite>=1.9.1
  - r-optparse>=1.7.5
  # naavre-fl-*-jupyter
  - ipykernel>=6.29.5
  - r-irkernel>=1.3.2
  # user packages for all flavors
  - git>=2.39.1
  - jq>=1.8
  - minio>=7.2.15
  - pip>=25.0.1
  - python>=3.10
  - r>=4.4
  - r-secretsprovider
  - r-getpass
  - r-aws.s3
  - pip:
    - SecretsProvider
  # user packages for this flavor
  - r-devtools
  - openssl
  - curl
  - wget
  - cmake
  - r-shiny
  - r-knitr
  - r-tidyverse
  - r-here
  - r-rgbif>=3.6.0
  - r-lubridate
  - r-base
  - r-glue
  - r-RSQLite
  - r-sp>=2.1-3
  - r-data.table
  - r-zip
  - r-assertable
  - r-assertthat
  - r-dplyr >=1.0
  - r-egg
  - r-forcats
  - r-ggplot2
  - r-leaflet
  - r-lifecycle
  - r-mgcv
  - r-plotly
  - r-purrr
  - r-readr
  - r-reshape2
  - r-rgbif >=3.0
  - r-rlang
  - r-rnaturalearth
  - r-scales
  - r-sf
  - r-stringr
  - r-svdialogs
  - r-tibble
  - r-tidyr
  - r-tidyselect >=1.2.0
  - zip
  - unzip
  - pandas
  - gdal
  - pyproj
  - shapely
  - r-sf
