name: Push image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Docker image name'
        type: string
        required: true
      image_repo:
        description: 'Docker image repo'
        type: string
        required: true
      old_image_version:
        description: 'Docker image version'
        type: string
        required: true
      new_image_version:
        description: 'Docker image version'
        type: string
        required: true
      free_disk_space:
        description: 'Free disk space on the action runner before running jobs'
        type: boolean
        required: false
        default: false

jobs:
  push:
    name: Push ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag image
        run: |
          echo docker buildx imagetools create \
            --tag ${{ inputs.image_repo }}/${{ inputs.image_name }}:${{ inputs.new_image_version }} \
            --tag ${{ inputs.image_repo }}/${{ inputs.image_name }}:latest \
            ${{ inputs.image_repo }}/${{ inputs.image_name }}:${{ inputs.old_image_version }}
